= Developer Guide
:toc:

== Setup
After checking out this project from github,

1. install JavaScript libraries and tools required by https://github.com/bensu/doo[doo]:
+
----
sudo npm install karma-cli -g
npm install
----
2. initialize cache for clj-kondo so it can lint against your dependencies
+
----
./script/lint.sh
----

== Testing During Development
Your personal preference will likely be different, but during maintenance and refactoring, I found running tests continuously for Clojure and ClojureScript helpful.

=== Clojure
For Clojure, I open a shell terminal window and run:

----
./script/clj-watch.sh
----

This launches https://github.com/lambdaisland/kaocha[kaocha] in watch mode.


=== ClojureScript
For Clojurescript, I open a shell terminal window and run:

----
./script/cljs-watch.sh
----

This launches https://figwheel.org/[fighweel main]. After the REPL is initialized navigate to http://localhost:9500/figwheel-extra-main/auto-testing to view auto-updating test results.

== Testing Before a Push
Before pushing, you likely want to mimic what we do up on https://circleci.com/[circleci].

----
./script/ci-tests.sh
----

== Linting
We use https://github.com/borkdude/clj-kondo[clj-kondo] for linting rewrite-cljc source code.

We fail the build on any lint violations. The ci server runs:
----
./script/lint.sh
----
and you can too.

https://github.com/borkdude/clj-kondo/blob/master/doc/editor-integration.md[Integrate clj-kondo into your editor] to catch mistakes as they happen.

== Contributors
We honor current and past contributors to rewrite-cljc in our README file.

To update contributors, update `doc/contributors.edn` then run `clojure -A:update-readme`.
