= Developer Guide
:toc:

== Supported Environments
All rewrite-cljc development has been done on macOS and we use linux for our builds up on circleci.

If circleci or GitHub Actions start to offer Windows as free build tool for open source projects
we will likely take advantage of that using Git Bash or equivalent.

We make use of planck for cljs bootstrap (aka self-hosted) testing. Planck is currently not available for Windows.
We'll test cljs bootstrap on Windows through some other mechanism when the time comes.

== Setup
After checking out this project from github,

1. install JavaScript libraries and tools required by https://github.com/bensu/doo[doo]:
+
----
sudo npm install karma-cli -g
npm install
----
2. https://github.com/planck-repl/planck#installing[install planck].

3. initialize cache for clj-kondo so it can lint against your dependencies
+
----
./script/lint.sh
----

== Testing During Development
Your personal preference will likely be different, but during maintenance and refactoring, I found running tests continuously for Clojure and ClojureScript helpful.

=== Clojure
For Clojure, I open a shell terminal window and run:

----
./script/clj-watch.sh
----

This launches https://github.com/lambdaisland/kaocha[kaocha] in watch mode.


=== ClojureScript
For Clojurescript, I open a shell terminal window and run:

----
./script/cljs-watch.sh
----

This launches https://figwheel.org/[fighweel main]. After the REPL is initialized navigate to http://localhost:9500/figwheel-extra-main/auto-testing to view auto-updating test results.

== Testing Before a Push
Before pushing, you likely want to mimic what we do up on https://circleci.com/[circleci].

----
./script/ci-tests.sh
----

== Linting
We use https://github.com/borkdude/clj-kondo[clj-kondo] for linting rewrite-cljc source code.

We fail the build on any lint violations. The ci server runs:
----
./script/lint.sh
----
and you can too.

https://github.com/borkdude/clj-kondo/blob/master/doc/editor-integration.md[Integrate clj-kondo into your editor] to catch mistakes as they happen.

== API diffs

To generate reports on differences between rewrite-clj, rewrite-cljs and
rewrite-cljc APIs, run `script/gen-api-diffs.sh`.

Ru this script manually on an as-needed basis. Generated reports are checked in
to version control.

Reports are generated to `doc/generated/api-diffs/` and include manually written
notes from `doc/diff-notes/`.

These reports are referenced from other docs, so if you rename files, be sure to
search for links.

Makes use of https://github.com/lread/diff-apis[diff-apis]. Delete
`.diff-apis/.cache` if you need a clean run.

== Contributors
We honor current and past contributors to rewrite-cljc in our README file.

To update contributors, update `doc/contributors.edn` then run `clojure -A:update-readme`.
