= Frequently Asked Questions

== Documentation

=== What is the meaning of the ^:no-doc metadata?
Our goal is to produce documentation for users of rewrite-cljc. As such we only want to document public APIs.

`^:no-doc` is a signal to https://cljdoc.org/[cljdoc] that source code should not be included in generated documentation. This metadata was introduced by https://github.com/weavejester/codox[codox]. Cljdoc uses a fork of codox internally.

== Why use AsciiDoc?
https://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc] is a markup language. We chose it for Clojure doc strings and general documentation because:

1. it is a richer markup language the GitHub markdown.
2. is supported by cljdoc.

We continue to leave the README in GitHub markdown because it is the introduction people will read when coming to our project from GitHub so we use the markdown language of GitHub to ensure it will format well.
Note that GitHub does partially support AsciiDoc but will not properly render all features.
