(ns rewrite-clj.doo-test-runner
  (:require [doo.runner :refer-macros [doo-all-tests]]
            [rewrite-clj.examples.cljx-test]
            [rewrite-clj.custom-zipper.core-test]
            [rewrite-clj.custom-zipper.utils-test]
            [rewrite-clj.node.coercer-test]
            [rewrite-clj.node.generators]
            [rewrite-clj.node.integer-test]
            [rewrite-clj.node.node-test]
            [rewrite-clj.potemkin-test]
            [rewrite-clj.zip.base-test]
            [rewrite-clj.zip.editz-test]
            [rewrite-clj.zip.findz-test]
            [rewrite-clj.zip.insert-test]
            [rewrite-clj.zip.move-test]
            [rewrite-clj.zip.removez-test]
            [rewrite-clj.zip.seqz-test]
            [rewrite-clj.zip.subedit-test]
            [rewrite-clj.zip.walk-test]
            [rewrite-clj.zip.whitespace-test]
            [rewrite-clj.node-test]
            [rewrite-clj.paredit-test]
            [rewrite-clj.parser-test]
            [rewrite-clj.regression-test]
            [rewrite-clj.transform-test]
            [rewrite-clj.zip-test]))

(doo-all-tests #"(rewrite-clj\..*-test)")
